apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: doorman
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups: ["doorman.zeromagic.io"]
    resources: ["scalingpolicies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: doorman
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: doorman
subjects:
  - kind: ServiceAccount
    name: doorman
    namespace: doorman-system
